on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: generate release files
        run: |
          mkdir dist
          echo "this is test release file" > dist/release.txt
          echo "this is test release file 2" > dist/release2.txt

      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: dist/**

      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: dist
