on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: generate release file
        run: echo "this is test release file" > release.txt

      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: release.txt

      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.txt
